### PR TITLE
Bugfix: Remove --zeek-dist argument from zkg.meta

### PR DESCRIPTION
**Pull request by rdylanwalker**
Issue: --zeek-dist argument causes installation failure.  Tests fail and should be updated. VERSION out of date.
    
Solution: Remove --zeek-dist arguement from configure.  Update tests. Update VERSION.

@keithjjones Unsure why, but `cd tests && btest` will pass locally, but when I tried to `zkg install ...` it would fail, but not give a reason.  Maybe you have some insight and can help if you see the same result?

### CODE REVIEW

**Comment by rdylanwalker** [comment]
Another strange issue I'm seeing.  When I `./configure && make && sudo make install`, the plugin works as expected.

However, if I `zkg install ...` either from master branch or my bugfix branch (with the zkg.meta update only), I cannot run the test zeek script.  `sudo zeek -N` errors:
```
error in /usr/local/zeek/share/zeek/base/init-bare.zeek, line 1: cannot load plugin library /usr/local/zeek/lib64/zeek/plugins/packages/zeek-jpeg//lib/Zeek-JPEG.linux-x86_64.so: /usr/local/zeek/lib64/zeek/plugins/packages/zeek-jpeg//lib/Zeek-JPEG.linux-x86_64.so: undefined symbol: _ZN4zeek6detail11DebugLogger7streamsE
fatal error in /usr/local/zeek/share/zeek/base/init-bare.zeek, line 1: aborting after plugin errors
```

Can you confirm you see something similar?

**Comment by rdylanwalker** [comment]
Solved the above errors with tests and the failure by removing the `--enable-debug` argument or taking out the DebugLogger and DBG statements from jpeg-analyzer.pac.  I'm unsure why including the DebugLogger causes an issue though.  Perhaps someone can enlighten me?

**Comment by rdylanwalker** [comment]
I opted to remove the `DBG_LOG` statements because I could not find examples of these in other Corelight repositories.  Feel free to let me know if you prefer to keep them and I will try to find a solution (though I may need some assistance).

**Comment by keithjjones** [comment]
Holy cow you rock!  I'm gonna test quickly locally and then merge.  Thanks for all this work!

**Comment by keithjjones** [comment]
Works on my macbook too.  Thanks!

**Pull request merged**
